### ISSUE TITLE
TLOS logo in Metamask is not visible

### ISSUE THREAD

**Issue by ezra-guzman** [telosnetwork/telos-wallet#360]
See image. The logo for TLOS must be updated to the version with a purple background.

https://raw.githubusercontent.com/telosnetwork/images/master/logos_2021/Symbol%202.svg

![Image](https://user-images.githubusercontent.com/11837820/241342041-907808e3-ea84-4c54-8e28-22fea5f022a7.png)

**Comment by Viterbo** [comment]
I'm suspecting that it must be some kind of network whitelist.
See those other examples of networks. Only Binance (and of course Ethereum) show their icons.
And is not an icon format because I did try ti add Telos EVM using the Binance icon and it didn't work.

- Akroma
![image](https://github.com/telosnetwork/telos-wallet/assets/4420760/a2c90b57-b5fa-4909-96e8-1173f81ae12c)

- Velas EVM
![image](https://github.com/telosnetwork/telos-wallet/assets/4420760/a50586dd-eb3a-4610-af09-83f824bbaa79)

- EraSwap
![image](https://github.com/telosnetwork/telos-wallet/assets/4420760/0f0ce69d-a647-4dce-a1d1-46ea2fa293b5)

- Binance
![image](https://github.com/telosnetwork/telos-wallet/assets/4420760/5208ebca-374d-4b9c-9589-dc6d3423c8e4)

**Comment by Viterbo** [comment]
I did the following test:
- I added a new EVM chain for the real BNB Smart Shain
- I created a Demo page for login into other EVM chains (and test multichain support)
- I did provide the URL for the Coingeko icon and the resulting icon is used from Metamask's local assets

![image](https://github.com/telosnetwork/telos-wallet/assets/4420760/50e24800-3985-4740-b737-6e56699bb16e)
![image](https://github.com/telosnetwork/telos-wallet/assets/4420760/7350ecdc-4bf3-49d5-9d73-4410123fa352)
![image](https://github.com/telosnetwork/telos-wallet/assets/4420760/75712f93-79b8-47f3-a044-c2a124ff475c)

**Comment by donnyquixotic** [comment]
Network and token logos are only auto-displayed for 'top' networks & tokens. See https://ethereum.stackexchange.com/questions/132988/logo-not-appearing-on-metamask/151701#151701
