### ISSUE TITLE
make git ignore the yarn.lock file

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/telos-wallet#61]
## Description
It makes no sense to version this file because is autogenerated each time you update packages by the yarn command. So it should be ignored by default by git.

## Tasks
- [ ] include yarn.lock in .gitignore file

**Comment by karynemayer** [comment]
@Viterbo It does help keep consistent [versioning between multiple dev environments](https://stackoverflow.com/questions/39990017/should-i-commit-the-yarn-lock-file-and-what-is-it-for). I think is worth keeping it and keeping it updated since we do, sometimes, have more than one person working on a project.

@donnyquixotic

**Comment by donnyquixotic** [comment]
Agree with @karynemayer can also see [here for more explanation](https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/)
