### ISSUE TITLE
NFT not displaying

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/telos-wallet#761]
**Describe the bug**
An NFT from a specific collection isn't displaying.

**To Reproduce**
1. Sign in with TCD testing account
2. Click 'digital collectibles'
3. See screenshot

**Screenshots**
![image](https://github.com/telosnetwork/telos-wallet/assets/6848910/bd680f88-8668-4fd9-b636-62ee845ed8c9)

**Additional context**
- newly minted from https://app.nft.ghostchain.io/, collection address: 0x91ba8A14D2CC851aBb69212c09f59e06e1e7f0a5 
- may a latency issue with indexer, if it is displaying at time of review disregard and close issue

**Comment by Viterbo** [comment]
The are some NFTs of the same collection showing perfectly fine like:
[#1 John McAfee Legacy](http://localhost:8081/evm/collectible-details?contract=0x91ba8A14D2CC851aBb69212c09f59e06e1e7f0a5&id=1&tab=attributes)
![image](https://github.com/telosnetwork/telos-wallet/assets/4420760/9232347a-994f-4df1-9fe3-c19657851aa8)

The image link is this one and it loads an image perfectly:
https://dweb.link/ipfs/QmXZfDpJrtCwS7dFKwyFRBJkTph2QHM6jMR45AjrAhxXDB/5352.png

However, there are some other NFTS like [#34 John McAfee Legacy](http://localhost:8081/evm/collectible-details?contract=0x91ba8A14D2CC851aBb69212c09f59e06e1e7f0a5&id=34&tab=attributes) which image like is broken like:
https://dweb.link/ipfs/QmXZfDpJrtCwS7dFKwyFRBJkTph2QHM6jMR45AjrAhxXDB/4215.png

Note is the same CID QmXZfDpJrtCwS7dFKwyFRBJkTph2QHM6jMR45AjrAhxXDB.

I'm closing this issue since is a problem of the user creator who did not check all images on IPFS
